 public async Task Get_WhenExceptionThrown_ReturnsInternalServerError()
    {
        // Arrange
        var serviceProvider = new ServiceCollection()
            .AddSingleton<ExceptionHandlingMiddleware>()
            .BuildServiceProvider();

        var middleware = serviceProvider.GetService<ExceptionHandlingMiddleware>();

        var context = new DefaultHttpContext();
        context.RequestServices = serviceProvider;

        _mockService.Setup(service => service.GetById(It.IsAny<int>())).Throws(new Exception("Test exception"));

        // Act
        var result = await middleware.InvokeAsync(context);

        // Assert
        var statusCodeResult = Assert.IsType<ObjectResult>(result);
        Assert.Equal(StatusCodes.Status500InternalServerError, statusCodeResult.StatusCode);
    }
